version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pdu-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - postgres-network

volumes:
  postgres_data:

# networks:
#   postgres-network:
